### ISSUE TITLE
Using quarto over ssh via tramp

### ISSUE THREAD

**Issue by aramirezreyes** [quarto-dev/quarto-emacs#20]
I think this project is basically unmaintained but this is worth a shot.

I work on a cluster editing a `.qmd` file via tramp (let's say `C-x C-f /ssh:dev_node:testingr/explore_tracks.qmd`).

1.- If I try to do quarto-preview I get a blank buffer with nothing showing.
2.- Inspecting the variable `quarto-command` I see that its value is nil. This is because emacs is looking for quarto in my local machine instead of `dev_node` and I do not have installed it.
3.- If I install quarto in my local machine and try `M-x quarto-preview` again, I get:

```
ERROR: /ssh:dev_node:/home/aramirezreyes/testingr/explore_tracks.qmd not found

Error: /ssh:dev_node:/home/aramirezreyes/testingr/explore_tracks.qmd not found
    at Command.fn (file:///Applications/quarto/bin/quarto.js:103602:15)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8437:13)
    at async quarto (file:///Applications/quarto/bin/quarto.js:127545:5)
    at async file:///Applications/quarto/bin/quarto.js:127563:9

Process quarto-preview-/ssh:dev_node:/home/aramirezreyes/testingr/explore_tracks.qmd exited abnormally with code 1
```

This is because my local quarto cannot find the remote file.

How could I get this setup to work? Any pointers to implement it if it is currently not working?

As an additional data point. The quarto extension for vscode works just fine over ssh so I guess it could be done.

Thank you!

**Comment by cscheid** [comment]
It's not unmaintained (I'm still taking PRs from people and fixes as they come) but I don't use it anymore on a daily basis, no there's no active development.

Adding tramp support for quarto-emacs and quarto preview is a big feature that I think would require a fair amount of emacs knowledge for you to implement.

> The quarto extension for vscode works just fine over ssh so I guess it could be done.

I'm not sure _how_ it works. I assume it's proxying the remote quarto preview HTTP server to a local one, and that's what you'd have to do as well.

**Comment by aramirezreyes** [comment]
Thanks for the answer! I did not want to be inflammatory with the unmaintained status, my apologies if it sounded that way.
I am definitely not on a huge level of emacs/elisp so I guess I am of little help here, would it be okay to leave it open in case someone more equipped comes looking for this?

**Comment by cscheid** [comment]
Yes, of course (and no worries about what you said, I just want to be clear so other readers don't get the wrong impression).

It would be a very fine and emacs-y thing to implement, it's just literally a matter of so many hours in the day.
